// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpblHl67picL8Bz-t7NKPrWFgH9IIoUL0',
    appId: '1:776758995967:web:8d43379b86fbdb2977d5ca',
    messagingSenderId: '776758995967',
    projectId: 'proxy-gen-8d56a',
    authDomain: 'proxy-gen-8d56a.firebaseapp.com',
    storageBucket: 'proxy-gen-8d56a.appspot.com',
    measurementId: 'G-R35VZQTV7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUYpCIKGMW2gjDPj918VI-r42hvTHBLGE',
    appId: '1:776758995967:android:1b2a81ef10976a2577d5ca',
    messagingSenderId: '776758995967',
    projectId: 'proxy-gen-8d56a',
    storageBucket: 'proxy-gen-8d56a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASNJRtVQbI8ju5n4WkNT4RIx74RW7V12c',
    appId: '1:776758995967:ios:e748678243b0c90d77d5ca',
    messagingSenderId: '776758995967',
    projectId: 'proxy-gen-8d56a',
    storageBucket: 'proxy-gen-8d56a.appspot.com',
    iosBundleId: 'com.example.proxyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASNJRtVQbI8ju5n4WkNT4RIx74RW7V12c',
    appId: '1:776758995967:ios:189452e2ce9c037477d5ca',
    messagingSenderId: '776758995967',
    projectId: 'proxy-gen-8d56a',
    storageBucket: 'proxy-gen-8d56a.appspot.com',
    iosBundleId: 'com.example.proxyapp.RunnerTests',
  );
}
