// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeObESzpB_A-ym3jTmIpd9z1q-lDkyH8E',
    appId: '1:944392652137:android:e5bab7de3cd58d45be29f8',
    messagingSenderId: '944392652137',
    projectId: 'proxyapp-e8a6f',
    storageBucket: 'proxyapp-e8a6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-HbOloyPnHKCfc38MjTZbWRsaDYlPVZg',
    appId: '1:944392652137:ios:d0d458a856201fb3be29f8',
    messagingSenderId: '944392652137',
    projectId: 'proxyapp-e8a6f',
    storageBucket: 'proxyapp-e8a6f.appspot.com',
    androidClientId:
        '944392652137-2ba9vucr57fhk3j1ka8qn5qu9e048r19.apps.googleusercontent.com',
    iosClientId:
        '944392652137-t0mhg8v98ii3kgeqcrcjr46bpuhh1ghc.apps.googleusercontent.com',
    iosBundleId: 'com.example.proxyapp',
  );
}
